// src/components/TablePriceByDate.vue
<script setup lang="ts">
import { formatDateChinese } from '../modules/date'
import { computed } from 'vue'
import { uniq } from 'lodash-es'
import { type Iphone, type IphoneModel } from '../types/Iphone'
import { type StorageSize } from '../types/StorageSize'
import { formatPrice } from '../modules/price'
import { formatStorageSize } from '../modules/storageSize'
import { formatIphoneModel } from '../modules/iphoneModel'
import AdjustedPrice from './AdjustedPrice.vue'
import { type Nullish } from '../types/Nullish'
import { findAdjustedList } from '../databases/iphone'

const props = defineProps<{
  date: Nullish<string>
  list: Nullish <Iphone[]>
}>()

const columns = computed(() => (
  uniq(props.list?.map(iphone => iphone.storage))
    .sort((a, b) => a - b)
))

const rows = computed(() => {
  const map: Partial<Record<IphoneModel, Partial<Record<StorageSize, Iphone>>>> = {}
  props.list?.forEach(iphone => {
    map[iphone.model] ??= {}
    ;(map[iphone.model] as Record<StorageSize, Iphone>)[iphone.storage] = iphone
  })
  return Object.values(map)
})
</script>

<template>
  <div class="flex w-full flex-col items-start gap-4">
    <h3 class="text-xl font-medium">
      {{ formatDateChinese(date) }}
    </h3>
    <div class="w-full min-w-0">
      <div class="overflow-x-auto overflow-y-hidden pb-6">
        <table class="table">
          <thead>
            <tr>
              <th>型號</th>
              <th v-for="column in columns" :key="column">
                {{ formatStorageSize(column) }}
              </th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(row, key) in rows" :key="key" class="hover">
              <td class="font-bold">
                <a
                  class="underline decoration-neutral-500 hover:decoration-neutral-400"
                  :href="Object.values(row)[0].url"
                  target="_blank"
                >
                  {{ formatIphoneModel(Object.values(row)[0]?.model) }}
                </a>
              </td>
              <td v-for="column in columns" :key="column" class="align-top">
                <div class="flex flex-col items-start">
                  <span class="font-rubik text-lg font-bold">
                    {{ formatPrice(row[column]?.price.twd) }}
                  </span>

                  <AdjustedPrice
                    v-for="(iphone, index) in findAdjustedList(column, Object.values(row)[0]?.model)"
                    :key="index"
                    :original="
                      findAdjustedList(column, Object.values(row)[0]?.model)?.[index - 1]?.price.twd ??
                        row[column]?.price.twd
                    "
                    :releasedAt="iphone.releasedAt"
                    :value="iphone?.price.twd"
                  />
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

// src/components/SectionTable/TablePriceByDate.tsx
import { useMemo } from 'react'
import { uniq } from 'lodash-es'
import { formatDateChinese } from '../../modules/date'
import { formatPrice } from '../../modules/price'
import { formatStorageSize } from '../../modules/storageSize'
import { formatIphoneModel } from '../../modules/iphoneModel'
import AdjustedPrice from './AdjustedPrice'
import type { Iphone, IphoneModel } from '../../types/Iphone'
import type { StorageSize } from '../../types/StorageSize'
import type { Nullish } from '../../types/Nullish'
import { findAdjustedList } from '../../databases/iphone'
import { StyledLink } from '../StyledLink'

interface Props {
  date: Nullish<string>
  list: Nullish<Iphone[]>
}

interface Row {
  model: IphoneModel
  byStorage: Partial<Record<StorageSize, Iphone>>
  firstUrl?: string
}

export default function IphonePriceTable({ date, list }: Props) {
  const columns = useMemo<StorageSize[]>(
    () =>
      uniq((list ?? []).map((iphone) => iphone.storage)).sort((a, b) => a - b),
    [list],
  )

  const rows = useMemo<Row[]>(() => {
    const map = new Map<IphoneModel, Row>()

    ;(list ?? []).forEach((iphone) => {
      if (!map.has(iphone.model)) {
        map.set(iphone.model, {
          model: iphone.model,
          byStorage: {},
          firstUrl: iphone.url,
        })
      }
      const row = map.get(iphone.model)
      if (!row) return

      row.byStorage[iphone.storage] = iphone
      if (!row.firstUrl && iphone.url) row.firstUrl = iphone.url
    })

    return Array.from(map.values())
  }, [list])

  return (
    <div className="flex w-full flex-col items-start gap-4">
      <h3 className="text-xl font-bold text-base-content/80">
        {formatDateChinese(date)}
      </h3>

      <div className="w-full min-w-0">
        <div className="overflow-x-auto overflow-y-hidden pb-6">
          <table className="w-full text-left">
            <thead className="text-xs font-bold text-base-content/60">
              <tr className="border-b border-base-content/10">
                <th className="px-4 py-3 align-middle">型號</th>
                {columns.map((col) => (
                  <th key={col} className="px-4 py-3">
                    {formatStorageSize(col)}
                  </th>
                ))}
              </tr>
            </thead>

            <tbody>
              {rows.map((row) => (
                <tr
                  key={row.model}
                  className="border-b border-base-content/10 last:border-b-0 hover:bg-base-content/10"
                >
                  <td className="px-4 py-3 align-top font-bold">
                    {row.firstUrl ? (
                      <StyledLink href={row.firstUrl} target="_blank">
                        {formatIphoneModel(row.model)}
                      </StyledLink>
                    ) : (
                      <span>{formatIphoneModel(row.model)}</span>
                    )}
                  </td>

                  {columns.map((col) => {
                    const iphone = row.byStorage[col]
                    const priceTwd = iphone?.price.twd
                    const adjustedList = findAdjustedList(col, row.model)

                    return (
                      <td key={col} className="px-4 py-3 align-top">
                        <div className="flex flex-col items-start">
                          <span className="font-rubik text-lg font-bold">
                            {formatPrice(priceTwd)}
                          </span>

                          {adjustedList.map((iphone, index) => {
                            const prev =
                              adjustedList[index - 1]?.price.twd ?? priceTwd
                            return (
                              <AdjustedPrice
                                key={index}
                                original={prev}
                                releasedAt={iphone.releasedAt}
                                value={iphone.price.twd}
                              />
                            )
                          })}
                        </div>
                      </td>
                    )
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
