// src/components/CheckboxGroupIphoneLine.vue
<script setup lang="ts">
import { useVModel } from '@vueuse/core'
import Checkbox from './Checkbox.vue'
import { type IphoneLine } from '../types/Iphone'
import { iphoneLines } from '../modules/iphoneLine'

const props = defineProps<{
  modelValue: IphoneLine[]
}>()

const emit = defineEmits<{
  'update:modelValue': [value: IphoneLine[]]
}>()

const options: IphoneLine[] = [
  'premium',
  'regular',
  'entry-level',
]

const vModel = useVModel(props, 'modelValue', emit)
</script>

<template>
  <div class="flex flex-wrap items-start gap-x-3">
    <div v-for="item in options" :key="item">
      <Checkbox
        v-model="vModel"
        :label="iphoneLines[item].name"
        :value="item"
      />
    </div>
  </div>
</template>

// src/components/SectionChart/CheckboxGroupIphoneLine.tsx
import { iphoneLineSchema, type IphoneLine } from '../../types/Iphone'
import { iphoneLines } from '../../modules/iphoneLine'
import { Checkbox } from '../Checkbox'

const options = iphoneLineSchema.options

export function CheckboxGroupIphoneLine({
  value,
  onChange,
}: {
  value: IphoneLine[]
  onChange: (value: IphoneLine[]) => void
}) {
  return (
    <div className="flex flex-wrap items-start gap-2">
      {options.map((item) => {
        const checked = value.includes(item)
        return (
          <div key={item}>
            <Checkbox
              checked={checked}
              onChange={(checked) => {
                if (checked) {
                  if (!value.includes(item)) onChange([...value, item])
                } else {
                  onChange(value.filter((valueItem) => valueItem !== item))
                }
              }}
              label={iphoneLines[item].name}
            />
          </div>
        )
      })}
    </div>
  )
}
