// src/App.vue
<script setup lang="ts">
import { defineAsyncComponent, ref } from 'vue'
import TheHero from './components/TheHero.vue'
import TheFooter from './components/TheFooter.vue'
import IconButtonDarkMode from './components/IconButtonDarkMode.vue'
import DataSource from './components/DataSource.vue'

const SectionChart = defineAsyncComponent(async () =>
  await import('./components/SectionChart.vue')
)

const SectionTable = defineAsyncComponent(async () =>
  await import('./components/SectionTable.vue')
)

const mainRaf = ref<HTMLElement | null>(null)
function scrollToMain () {
  mainRaf.value?.scrollIntoView({ behavior: 'smooth' })
}
</script>

<template>
  <TheHero @clickViewChart="scrollToMain" />

  <main
    ref="mainRaf"
    class="container min-h-screen space-y-20 px-4 py-6"
  >
    <SectionChart />
    <SectionTable />

    <div class="mx-auto max-w-2xl space-y-4">
      <DataSource />
    </div>
  </main>

  <TheFooter />

  <div class="fixed bottom-4 right-4 z-[100]">
    <IconButtonDarkMode />
  </div>
</template>

// src/app/page.tsx
'use client'

import { Hero } from '@/src/components/Hero'
import Footer from '../components/Footer'
import { useRef } from 'react'
import { DataSource } from '../components/DataSource'
import { SectionTable } from '../components/SectionTable'
import { SectionChart } from '../components/SectionChart'

export default function Home() {
  const chartRef = useRef<HTMLElement | null>(null)
  const tableRef = useRef<HTMLElement | null>(null)

  function scrollToChart() {
    chartRef.current?.scrollIntoView({ behavior: 'smooth' })
  }
  function scrollToTable() {
    tableRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  return (
    <>
      <Hero onClickViewChart={scrollToChart} onClickViewTable={scrollToTable} />
      <main className="container min-h-screen space-y-20 px-4 py-6">
        <SectionChart ref={chartRef} />
        <SectionTable ref={tableRef} />
        <div className="space-y-4">
          <DataSource />
        </div>
      </main>
      <Footer />
    </>
  )
}
