// src/components/SectionChart/Chart.tsx
import { TaiwanMinimumWage } from '@/src/databases/taiwanMinimumWage'
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { LineChart } from 'echarts/charts'
import {
  type LineSeriesOption,
  type EChartsOption,
  type DatasetComponentOption,
} from 'echarts'
import {
  DatasetComponent,
  TooltipComponent,
  GridComponent,
  MarkLineComponent,
} from 'echarts/components'
import ReactECharts from 'echarts-for-react'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import colors from 'tailwindcss/colors'
import {
  formatIphoneModelAbbreviation,
  formatIphoneModel,
} from '@/src/modules/iphoneModel'
import { formatPriceAbbreviation, formatPrice } from '@/src/modules/price'
import { Iphone } from '@/src/types/Iphone'
import dayjs from 'dayjs'
import { Nullish } from '@/src/types/Nullish'
import { useChartTooltip } from './useChartTooltip'
import { CardNoResult } from './CardNoResult'

// eslint-disable-next-line react-hooks/rules-of-hooks
use([
  CanvasRenderer,
  LineChart,
  DatasetComponent,
  TooltipComponent,
  GridComponent,
  MarkLineComponent,
])

export default function Chart(props: {
  iphoneDataset: DatasetComponentOption[]
  taiwanMinimumWageList: TaiwanMinimumWage[]

  selectedSeriesName?: string | null
  onChangeSelectedSeriesName?: (index: string | null) => void

  modelNameAbbreviation: boolean
  priceAbbreviation: boolean
  hidePrice: boolean
  hideTooltip: boolean

  showTaiwanMinimumWageList: boolean
  onReset?: () => void
}) {
  const selectedSeriesNameRef = useRef(props.selectedSeriesName)
  selectedSeriesNameRef.current = props.selectedSeriesName

  const [isDark] = useState(true)
  const shade = isDark ? 800 : 600
  const commonLabelRich = useMemo(
    () =>
      ({
        textBorderWidth: 2,
        textBorderColor: isDark ? 'rgba(0,0,0,.7)' : 'rgba(255,255,255,.7)',
      }) as const,
    [isDark],
  )
  const labelRichPrice = useMemo(
    () => ({
      ...commonLabelRich,
      fontSize: 14,
      fontWeight: 600,
    }),
    [commonLabelRich],
  )
  const labelRichName = useMemo(
    () => ({
      ...commonLabelRich,
      color: colors.neutral[isDark ? 400 : 600],
      fontSize: props.hidePrice ? 12 : 10,
      fontWeight: props.hidePrice ? 500 : 400,
      lineHeight: 16,
      padding: [0, 4, 0, 0],
    }),
    [commonLabelRich, isDark, props.hidePrice],
  )

  const label = useMemo(
    () =>
      ({
        show: true,
        formatter(params) {
          const iphone = params.data as Iphone

          const { model } = iphone
          const formattedModelName = props.modelNameAbbreviation
            ? formatIphoneModelAbbreviation(model)
            : formatIphoneModel(model)

          const price = iphone.price.twd
          const formattedPrice = props.priceAbbreviation
            ? formatPriceAbbreviation(price)
            : formatPrice(price)

          return [
            `{name|${formattedModelName}}`,
            props.hidePrice ? null : `{price|${String(formattedPrice)}}`,
          ]
            .filter(Boolean)
            .join(props.modelNameAbbreviation ? '' : '\n')
        },
        rich: {
          name: labelRichName,
          price: labelRichPrice,
        },
      }) satisfies LineSeriesOption['label'],
    [
      labelRichName,
      labelRichPrice,
      props.hidePrice,
      props.modelNameAbbreviation,
      props.priceAbbreviation,
    ],
  )

  const taiwanMinimumWageLabel = useMemo<LineSeriesOption['label']>(
    () => ({
      show: true,
      formatter(params) {
        if (!Array.isArray(params.value)) return ''

        const price = Number(params.value[1])
        const formattedPrice = props.priceAbbreviation
          ? formatPriceAbbreviation(price)
          : formatPrice(price)
        const name = props.modelNameAbbreviation
          ? '月薪'
          : '台灣基本工資（月薪）'

        return [
          !params.dataIndex ? `{name|${name}}` : null,
          props.hidePrice ? null : `{price|${String(formattedPrice)}}`,
        ]
          .filter(Boolean)
          .join(props.modelNameAbbreviation ? '' : '\n')
      },
      rich: {
        name: labelRichName,
        price: labelRichPrice,
      },
    }),
    [
      labelRichName,
      labelRichPrice,
      props.hidePrice,
      props.modelNameAbbreviation,
      props.priceAbbreviation,
    ],
  )

  const taiwanMinimumWageSeriesName = '台灣基本工資（月薪）'
  const taiwanMinimumWageSeries: LineSeriesOption = useMemo(
    () => ({
      type: 'line',
      silent: true,
      smooth: true,
      symbol: 'roundRect',
      symbolSize: 8,
      label: taiwanMinimumWageLabel,
      color: isDark ? colors.zinc[400] : colors.zinc[700],
      emphasis: { focus: 'series' },
      encode: { x: 'date', y: 'value', itemName: 'name' },
      name: taiwanMinimumWageSeriesName,
      data: props.taiwanMinimumWageList.map((item) => ({
        name: taiwanMinimumWageSeriesName,
        date: +dayjs(item.implementedAt, 'YYYY-MM-DD'),
        value: [
          +dayjs(item.implementedAt, 'YYYY-MM-DD'),
          item.monthlySalary.twd,
        ],
      })),
    }),
    [isDark, props.taiwanMinimumWageList, taiwanMinimumWageLabel],
  )

  const { tooltip } = useChartTooltip()

  const option = useMemo(
    () =>
      ({
        darkMode: isDark,
        dataset: props.iphoneDataset,
        tooltip: props.hideTooltip ? undefined : tooltip,
        series: [
          ...props.iphoneDataset.map<LineSeriesOption>((dataset, index) => ({
            type: 'line',
            label,
            symbol: 'circle',
            symbolSize: 6,
            smooth: true,
            encode: { x: 'date', y: 'value', itemName: 'name' },
            datasetIndex: index,
            name: dataset.name,
            id: dataset.name,
            emphasis: { focus: 'series', scale: 1.5 },
            triggerLineEvent: true,
          })),
          ...(props.showTaiwanMinimumWageList ? [taiwanMinimumWageSeries] : []),
        ],
        animationDuration: 200,
        animationDurationUpdate: 350,
        textStyle: { fontFamily: ['Rubik', '"Noto Sans TC"'].join(',') },
        color: [
          colors.rose[shade],
          colors.amber[shade],
          colors.lime[shade],
          colors.cyan[shade],
          colors.teal[shade],
          colors.indigo[shade],
          colors.orange[shade],
          colors.green[shade],
          colors.emerald[shade],
          colors.violet[shade],
        ],
        grid: {
          containLabel: true,
          top: '8%',
          right: '4%',
          bottom: '0%',
          left: '4%',
        },
        xAxis: {
          type: 'time',
          minInterval: 24 * 3600 * 1000,
          splitNumber: 5,
          boundaryGap: ['5%', '5%'],
          axisLabel: {
            formatter: '{yyyy}-{MM}',
            showMaxLabel: true,
            showMinLabel: true,
          },
        },
        yAxis: {
          type: 'value',
          min: 'dataMin',
          axisLabel: { formatter: formatPriceAbbreviation },
          splitLine: { lineStyle: { color: isDark ? '#666' : '#ccc' } },
        },
      }) satisfies EChartsOption,
    [
      isDark,
      label,
      props.hideTooltip,
      props.iphoneDataset,
      props.showTaiwanMinimumWageList,
      shade,
      taiwanMinimumWageSeries,
      tooltip,
    ],
  )

  const isEmpty = !props.iphoneDataset.length

  const chartRef = useRef<ReactECharts | null>(null)

  const handleClick = useCallback(
    (event: { seriesName: Nullish<string> }) => {
      if (event.seriesName === taiwanMinimumWageSeriesName) return

      const callback = props.onChangeSelectedSeriesName
      callback?.(event.seriesName ?? null)
    },
    [props.onChangeSelectedSeriesName],
  )

  const highlight = useCallback(() => {
    const seriesName = selectedSeriesNameRef.current
    const instance = chartRef.current?.getEchartsInstance()

    if (!seriesName) {
      const series = instance?.getOption().series as LineSeriesOption[]
      instance?.dispatchAction({
        type: 'highlight',
        seriesName: series.map((series) => series.name),
      })
      instance?.dispatchAction({ type: 'downplay' })
    } else {
      instance?.dispatchAction({ type: 'highlight', seriesName })
    }
  }, [])

  useEffect(() => {
    highlight()
  }, [highlight, props.selectedSeriesName])

  const handleMouseOut = useCallback(() => {
    void (async () => {
      await new Promise((resolve) => setTimeout(resolve, 10))
      highlight()
    })()
  }, [highlight])

  const onEvents = useMemo(
    () => ({
      click: handleClick,
      mouseout: handleMouseOut,
    }),
    [handleClick, handleMouseOut],
  )

  if (isEmpty) return <CardNoResult onReset={props.onReset} />

  return (
    <div
      className="size-full min-w-[800px] overflow-hidden sm:min-w-0"
      onMouseOut={handleMouseOut}
    >
      <ReactECharts
        ref={(e) => {
          chartRef.current = e
        }}
        notMerge
        className="!size-full"
        option={option}
        onEvents={onEvents}
      />
    </div>
  )
}

// src/components/Chart.vue
<script setup lang="ts">
import { computed, nextTick, ref, watch } from 'vue'
import dayjs from 'dayjs'
import { type LineSeriesOption, type EChartsOption, type DatasetComponentOption } from 'echarts'
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { LineChart } from 'echarts/charts'
import VueECharts from 'vue-echarts'
import { DatasetComponent, TooltipComponent, GridComponent, MarkLineComponent } from 'echarts/components'
import { type Iphone } from '../types/Iphone'
import { formatIphoneModel, formatIphoneModelAbbreviation } from '../modules/iphoneModel'
import { useDark } from '../composables/useDark'
import colors from 'tailwindcss/colors'
import { formatPrice, formatPriceAbbreviation } from '../modules/price'
import CardNoResult from './CardNoResult.vue'
import { type TaiwanMinimumWage } from '../databases/taiwanMinimumWage'
import { useChartTooltip } from '../composables/useChartTooltip'

use([
  CanvasRenderer,
  LineChart,
  DatasetComponent,
  TooltipComponent,
  GridComponent,
  MarkLineComponent,
])

const props = defineProps<{
  selectedSeriesName?: string | null

  iphoneDataset: DatasetComponentOption[]
  taiwanMinimumWageList: TaiwanMinimumWage[]

  modelNameAbbreviation: boolean
  priceAbbreviation: boolean
  hidePrice: boolean
  hideTooltip: boolean

  showTaiwanMinimumWageList: boolean
}>()

const emit = defineEmits<{
  reset: []
  'update:selectedSeriesName': [index: string | null]
}>()

const isDark = useDark()
const shade = computed(() => isDark.value ? 800 : 600)

const commonLabelRich = computed(() => ({
  textBorderWidth: 2,
  textBorderColor: isDark.value
    ? 'rgba(0,0,0,.7)'
    : 'rgba(255,255,255,.7)',
} as const))

const labelRichPrice = computed(() => ({
  ...commonLabelRich.value,
  fontSize: 14,
  fontWeight: 600,
}))

const labelRichName = computed(() => ({
  ...commonLabelRich.value,
  color: colors.neutral[isDark.value ? 400 : 600],
  fontSize: props.hidePrice ? 12 : 10,
  fontWeight: props.hidePrice ? 500 : 400,
  lineHeight: 16,
  padding: [0, 4, 0, 0],
}))

const label = computed<LineSeriesOption['label']>(() => {
  const {
    modelNameAbbreviation: isModelNameAbbreviation,
    priceAbbreviation: isPriceAbbreviation,
    hidePrice: isPriceHidden,
  } = props

  return {
    show: true,
    formatter (params) {
      const iphone = params.data as Iphone

      const { model } = iphone
      const formattedModelName = isModelNameAbbreviation
        ? formatIphoneModelAbbreviation(model)
        : formatIphoneModel(model)

      const price = iphone.price.twd
      const formattedPrice = isPriceAbbreviation
        ? formatPriceAbbreviation(price)
        : formatPrice(price)

      return [
        `{name|${formattedModelName}}`,
        isPriceHidden ? null : `{price|${formattedPrice}}`,
      ]
        .filter(Boolean)
        .join(isModelNameAbbreviation ? '' : '\n')
    },
    rich: {
      name: labelRichName.value,
      price: labelRichPrice.value,
    },
  }
})

const taiwanMinimumWageLabel = computed<LineSeriesOption['label']>(() => {
  const {
    modelNameAbbreviation: isModelNameAbbreviation,
    priceAbbreviation: isPriceAbbreviation,
    hidePrice: isPriceHidden,
  } = props

  return {
    show: true,
    formatter (params) {
      if (!Array.isArray(params.value)) return ''

      const price = +params.value[1]
      const formattedPrice = isPriceAbbreviation
        ? formatPriceAbbreviation(price)
        : formatPrice(price)
      const name = isModelNameAbbreviation ? '月薪' : '台灣基本工資（月薪）'

      return [
        !params.dataIndex ? `{name|${name}}` : null,
        isPriceHidden ? null : `{price|${formattedPrice}}`,
      ]
        .filter(Boolean)
        .join(isModelNameAbbreviation ? '' : '\n')
    },
    rich: {
      name: labelRichName.value,
      price: labelRichPrice.value,
    },
  }
})

const taiwanMinimumWageSeriesName = '台灣基本工資（月薪）'
const taiwanMinimumWageSeries = computed<LineSeriesOption>(() => ({
  type: 'line',
  silent: true,
  smooth: true,
  symbol: 'roundRect',
  symbolSize: 8,
  label: taiwanMinimumWageLabel.value,
  color: isDark.value ? colors.zinc[400] : colors.zinc[700],
  emphasis: { focus: 'series' },
  encode: {
    x: 'date',
    y: 'value',
    itemName: 'name',
  },
  name: taiwanMinimumWageSeriesName,
  data: props.taiwanMinimumWageList.map((item) => ({
    name: taiwanMinimumWageSeriesName,
    date: +dayjs(item.implementedAt, 'YYYY-MM-DD'),
    value: [
      +dayjs(item.implementedAt, 'YYYY-MM-DD'),
      item.monthlySalary.twd,
    ],
  })),
}))

const { tooltip } = useChartTooltip()

const option = computed<EChartsOption>(() => ({
  darkMode: isDark.value,
  dataset: props.iphoneDataset,
  tooltip: props.hideTooltip ? undefined : tooltip.value,
  series: [
    ...props.iphoneDataset.map<LineSeriesOption>((dataset, index) => ({
      type: 'line',
      label: label.value,
      symbol: 'circle',
      symbolSize: 6,
      smooth: true,
      encode: {
        x: 'date',
        y: 'value',
        itemName: 'name',
      },
      datasetIndex: index,
      name: dataset.name,
      id: dataset.name,
      emphasis: {
        focus: 'series',
        scale: 1.3,
      },
      triggerLineEvent: true,
    })),
    ...(props.showTaiwanMinimumWageList
      ? [taiwanMinimumWageSeries.value]
      : []),
  ],
  animationDuration: 200,
  animationDurationUpdate: 350,
  textStyle: {
    fontFamily: ['Rubik', '"Noto Sans TC"'].join(','),
  },
  color: [
    colors.rose[shade.value],
    colors.amber[shade.value],
    colors.lime[shade.value],
    colors.cyan[shade.value],
    colors.teal[shade.value],
    colors.indigo[shade.value],
    colors.orange[shade.value],
    colors.green[shade.value],
    colors.emerald[shade.value],
    colors.violet[shade.value],
  ],
  grid: {
    containLabel: true,
    top: '8%',
    right: '4%',
    bottom: '0%',
    left: '4%',
  },
  xAxis: {
    type: 'time',
    minInterval: 24 * 3600 * 1000,
    splitNumber: 5,
    boundaryGap: ['5%', '5%'],
    axisLabel: {
      formatter: '{yyyy}-{MM}',
      showMaxLabel: true,
      showMinLabel: true,
    },
  },
  yAxis: {
    type: 'value',
    min: 'dataMin',
    axisLabel: {
      formatter: formatPriceAbbreviation,
    },
    splitLine: {
      lineStyle: {
        color: isDark.value ? '#666' : '#ccc',
      },
    },
  },
}))

const isEmpty = computed(() => !props.iphoneDataset.length)

const chartRef = ref<InstanceType<typeof VueECharts> | null>(null)

function handleClick (event: Parameters<NonNullable<InstanceType< typeof VueECharts>['onClick']>>[0]) {
  if (event.seriesName === taiwanMinimumWageSeriesName) return

  emit('update:selectedSeriesName', event.seriesName ?? null)
}

function highlight () {
  if (props.selectedSeriesName != null) {
    chartRef.value?.dispatchAction({
      type: 'highlight',
      seriesName: props.selectedSeriesName,
    })
  }
}

async function handleMouseOut () {
  await nextTick()
  highlight()
}

watch(() => props.selectedSeriesName, () => {
  if (!props.selectedSeriesName) {
    chartRef.value?.dispatchAction({
      type: 'downplay',
    })
  } else {
    highlight()
  }
})

function getDownloadUrl () {
  return chartRef.value?.getDataURL({ type: 'png' })
}

defineExpose({ getDownloadUrl })
</script>

<template>
  <CardNoResult v-if="isEmpty" @reset="$emit('reset')" />
  <div v-else class="h-full w-full overflow-hidden">
    <VueECharts
      ref="chartRef"
      autoresize
      class="h-full w-full"
      :option="option"
      @click="handleClick"
      @mouseout="handleMouseOut"
      @zr:mouseout="handleMouseOut"
    />
  </div>
</template>
