// src/components/Label.vue
<script setup lang="ts">
defineProps<{
  active?: boolean
  disabled?: boolean
  label?: string
}>()
</script>

<template>
  <label
    class="label relative cursor-pointer justify-start space-x-3 font-bold"
    :class="{
      'cursor-pointer': !disabled,
      'cursor-not-allowed': disabled,
    }"
  >
    <slot />
    <span
      class="label-text transition-colors duration-100"
      :class="{
        'text-primary': active,
        'opacity-50': disabled,
      }"
    >
      {{ label }}
    </span>
  </label>
</template>

// src/components/Label.tsx
import { PropsWithChildren } from 'react'
import { cn } from '../modules/cn'

export function Label({
  active,
  disabled,
  label,
  children,
}: PropsWithChildren<{
  active?: boolean
  disabled?: boolean
  label?: string
}>) {
  return (
    <label
      className={cn(
        'relative flex select-none items-center justify-start space-x-3 px-1 py-2 font-bold',
        disabled ? 'cursor-not-allowed' : 'cursor-pointer',
      )}
    >
      {children}
      <span
        className={cn('text-sm transition-colors duration-100', {
          'text-primary': active,
          'opacity-50': disabled,
        })}
      >
        {label}
      </span>
    </label>
  )
}
