// src/components/RangeSlider.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'

type ModelValue = [number, number]

const props = withDefaults(defineProps<{
  modelValue?: ModelValue
  min?: number
  max?: number
  step?: number
}>(), {
  modelValue: () => [0, 100],
  min: 0,
  max: 100,
  step: 1,
})

const emit = defineEmits<{
  'update:modelValue': [value: ModelValue]
}>()

const draft = ref<ModelValue>(props.modelValue)
watch(() => props.modelValue, async (modelValue) => {
  const serialize = (list: number[]) => [...list].sort((a, b) => a - b).join()
  if (serialize(modelValue) !== serialize(draft.value)) {
    draft.value = [...modelValue]
  }
})

function getPercent (value: number) {
  const { max, min } = props
  return Math.round(((value - min) / (max - min)) * 100)
}

const highlightStyle = computed(() => {
  let [left, right] = draft.value
  if (left > right) [left, right] = [right, left]

  const leftPercent = getPercent(left)
  const rightPercent = getPercent(right)

  return {
    left: `${leftPercent}%`,
    width: `${rightPercent - leftPercent}%`,
  }
})

function handleInput (event: Event, index: 0 | 1) {
  const target = event.target as HTMLInputElement
  const newDraft: ModelValue = [...draft.value]

  newDraft[index] = target.valueAsNumber
  draft.value = [...newDraft]

  const newSortedDraft = ([...newDraft] as ModelValue).sort((a, b) => a - b)
  emit('update:modelValue', newSortedDraft)
}

function handleChange () {
  draft.value = [...props.modelValue]
}

const ticks = computed(() => {
  const tickCount = Math.min(props.max - props.min / props.step) + 1
  return Array.from({ length: tickCount })
    .map((_, index) => index + props.min)
})
</script>

<template>
  <div class="relative space-y-2 px-1 py-2">
    <div class="relative flex h-6 w-full items-center">
      <input
        class="range range-primary"
        :max="max"
        :min="min"
        :step="step"
        type="range"
        :value="draft[0]"
        @change="handleChange"
        @input="handleInput($event, 0)"
      >
      <input
        class="range range-primary"
        :max="max"
        :min="min"
        :step="step"
        type="range"
        :value="draft[1]"
        @change="handleChange"
        @input="handleInput($event, 1)"
      >
      <div class="relative h-2 w-full overflow-hidden rounded-box bg-base-content/10">
        <div
          class="absolute h-full bg-primary"
          :style="highlightStyle"
        />
      </div>
    </div>

    <div class="flex w-full select-none justify-between">
      <span
        v-for="(tick, index) in ticks"
        :key="tick"
        class="flex w-6 justify-center text-xs font-bold"
      >
        <Transition
          enterActiveClass="transition duration-100"
          enterFromClass="scale-90"
          mode="out-in"
        >
          <span
            v-if="draft.includes(tick) || !index || index === ticks.length - 1"
            :class="draft.includes(tick) ? 'text-primary' : 'text-base-content/80'"
          >
            {{ tick }}
          </span>
          <span
            v-else
            class="after:inline-block after:h-2 after:w-[2px] after:rounded-full after:bg-base-content/80 after:content-['']"
          />
        </Transition>
      </span>
    </div>
  </div>
</template>

<style scoped lang="scss">
input.range {
  @apply absolute left-0 w-full h-full;
  @apply pointer-events-none;

  &::-webkit-slider-runnable-track {
    @apply bg-transparent;
  }
  &::-moz-range-track {
    @apply bg-transparent;
  }

  &::-webkit-slider-thumb {
    @apply pointer-events-auto;
    @apply z-10;
    @apply bg-primary;
    box-shadow:
      0 0 0 3px hsl(var(--range-shdw)) inset,
      var(--focus-shadow, 0 0);
  }

  &::-moz-range-thumb {
    @apply pointer-events-auto;
    @apply bg-primary;
    box-shadow:
      0 0 0 3px hsl(var(--range-shdw)) inset,
      var(--focus-shadow, 0 0);
  }
}
</style>

// src/components/RangeSlider.tsx
import {
  ChangeEvent,
  ComponentProps,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react'
import { cn } from '../modules/cn'
import { clamp } from 'lodash-es'

function RangeInput({ className, ...props }: ComponentProps<'input'>) {
  return (
    <input
      className={cn(
        `
          absolute left-0 size-full cursor-pointer appearance-none bg-transparent
          [&::-webkit-slider-runnable-track]:h-2
          [&::-webkit-slider-runnable-track]:bg-transparent

          [&::-webkit-slider-thumb]:pointer-events-auto
          [&::-webkit-slider-thumb]:relative
          [&::-webkit-slider-thumb]:top-1/2
          [&::-webkit-slider-thumb]:z-10
          [&::-webkit-slider-thumb]:size-6
          [&::-webkit-slider-thumb]:-translate-y-1/2
          [&::-webkit-slider-thumb]:appearance-none
          [&::-webkit-slider-thumb]:rounded-full
          [&::-webkit-slider-thumb]:bg-primary
        `,
        className,
      )}
      type="range"
      {...props}
    />
  )
}

const serializeSorted = (list: number[]) =>
  [...list].sort((a, b) => a - b).join()

type Value = [number, number]

export function RangeSlider({
  value = [0, 100],
  onChange,
  min = 0,
  max = 100,
  step = 1,
}: {
  value?: Value
  onChange?: (val: Value) => void
  min?: number
  max?: number
  step?: number
}) {
  const [draft, setDraft] = useState<Value>(value)

  const lastSerialized = useRef(serializeSorted(draft))
  useEffect(() => {
    const incoming = serializeSorted(value)
    if (incoming !== lastSerialized.current) {
      setDraft(value)
      lastSerialized.current = incoming
    }
  }, [value])

  const highlightStyle = useMemo(() => {
    const getPercent = (value: number) => {
      const percent = Math.round(((value - min) / (max - min)) * 100)
      return clamp(percent, 0, 100)
    }

    let [left, right] = draft
    if (left > right) [left, right] = [right, left]
    const leftPercent = getPercent(left)
    const rightPercent = getPercent(right)
    return {
      left: `${String(leftPercent)}%`,
      width: `${String(rightPercent - leftPercent)}%`,
    }
  }, [draft, min, max])

  const ticks = useMemo(() => {
    const count = Math.floor((max - min) / step) + 1
    return Array.from({ length: count }, (_, i) => min + i * step)
  }, [min, max, step])

  const commitChange = (next: Value) => {
    const sorted: Value = [...next].sort((a, b) => a - b) as Value
    lastSerialized.current = serializeSorted(sorted)
    onChange?.(sorted)
  }

  const handleInput = (index: 0 | 1) => (e: ChangeEvent<HTMLInputElement>) => {
    console.log('handleInput')
    const nextDraft: Value = [...draft]
    nextDraft[index] = e.target.valueAsNumber

    setDraft(nextDraft)
    commitChange(nextDraft)
  }

  return (
    <div className="relative space-y-2 px-1 py-2">
      <div className="relative flex h-6 w-full items-center">
        <RangeInput
          min={min}
          max={max}
          step={step}
          value={draft[0]}
          onInput={handleInput(0)}
        />
        <RangeInput
          min={min}
          max={max}
          step={step}
          value={draft[1]}
          onInput={handleInput(1)}
        />

        <div className="pointer-events-none relative flex h-2 w-full items-center justify-between overflow-hidden rounded-2xl bg-base-content/10">
          <div className="absolute h-full bg-primary" style={highlightStyle} />
          {ticks.map((tick) => (
            <span key={tick} className="flex w-6 justify-center">
              <span className="block size-0.5 rounded-full bg-base-content/30" />
            </span>
          ))}
        </div>
      </div>

      <div className="flex w-full select-none justify-between">
        {ticks.map((tick, index) => {
          const showNumber =
            draft.includes(tick) || !index || index === ticks.length - 1

          return (
            <span
              key={tick}
              className={cn(
                'flex w-6 items-center justify-center text-xs font-bold',
                'empty:after:inline-block empty:after:h-2 empty:after:w-0.5 empty:after:rounded-full empty:after:bg-base-content/50',
              )}
            >
              {showNumber && (
                <span
                  className={cn(
                    draft.includes(tick)
                      ? 'text-primary'
                      : 'text-base-content/80',
                  )}
                >
                  {tick}
                </span>
              )}
            </span>
          )
        })}
      </div>
    </div>
  )
}
