// src/components/SectionTable/index.tsx
import { forwardRef, PropsWithChildren, useMemo, useState } from 'react'
import groupBy from 'lodash-es/groupBy'
import dayjs from 'dayjs'
import { iphoneList } from '../../databases/iphone'
import { formatDateChinese } from '../../modules/date'
import TablePriceByDate from './TablePriceByDate'
import { cn } from '@/src/modules/cn'
import { NewBadge } from './NewBadge'
import { IconTableFilled } from '@tabler/icons-react'

function ListItem({
  active,
  onClick,
  children,
}: PropsWithChildren<{
  active?: boolean
  onClick: () => void
}>) {
  return (
    <li className="w-full">
      <button
        type="button"
        className={cn(
          'flex w-full select-none items-center justify-between rounded-[1.9rem] px-4 py-2 text-left',
          {
            'hover:bg-base-content/10': !active,
            'bg-primary text-primary-content font-bold': active,
          },
        )}
        onClick={onClick}
      >
        {children}
      </button>
    </li>
  )
}

export const SectionTable = forwardRef<HTMLElement>(
  function SectionTable(_, ref) {
    const groups = useMemo(
      () =>
        groupBy(
          iphoneList.filter((x) => x.isInitialRelease),
          'releasedAt',
        ),
      [],
    )

    const releaseDates = useMemo(
      () => Object.keys(groups).sort((a, b) => +dayjs(b) - +dayjs(a)),
      [groups],
    )

    const [selectedDate, setSelectedDate] = useState<string | null>(
      releaseDates[0] ?? null,
    )

    const displayed = useMemo(() => {
      if (selectedDate) {
        return [{ date: selectedDate, list: groups[selectedDate] }]
      }
      return releaseDates.map((date) => ({ date, list: groups[date] }))
    }, [groups, releaseDates, selectedDate])

    return (
      <section className="mx-auto flex max-w-5xl flex-col gap-y-8" ref={ref}>
        <h2 className="text-3xl font-bold">歷年首發機型</h2>

        <div className="flex flex-wrap gap-4">
          <div className="relative w-full lg:w-1/5">
            <div className="sticky top-4 flex flex-col gap-y-4">
              <h3 className="text-xl font-medium">發售年月</h3>

              <ul className="flex flex-col rounded-2xl bg-base-200 p-2 text-sm">
                <ListItem
                  active={!selectedDate}
                  onClick={() => {
                    setSelectedDate(null)
                  }}
                >
                  <span className="inline-flex items-center">
                    <IconTableFilled className="mr-2 inline-block" size={20} />
                    顯示全部
                  </span>
                </ListItem>

                {releaseDates.map((date, index) => {
                  const isActive = date === selectedDate

                  return (
                    <ListItem
                      key={date}
                      active={isActive}
                      onClick={() => {
                        setSelectedDate(date)
                      }}
                    >
                      {formatDateChinese(date)}
                      {!index && (
                        <NewBadge
                          className={cn(
                            'rounded-full border border-current bg-orange-500/10 px-1.5 text-xs font-bold text-orange-500',
                            { 'text-inherit bg-transparent': isActive },
                          )}
                        />
                      )}
                    </ListItem>
                  )
                })}
              </ul>
            </div>
          </div>

          <div className="flex min-w-full flex-col gap-4 sm:mx-0 sm:flex-1 lg:min-w-0 lg:px-8">
            {displayed.map(({ date, list }, index) => (
              <TablePriceByDate key={index} date={date} list={list} />
            ))}

            <span className="text-xs opacity-70">單位：新台幣</span>
          </div>
        </div>
      </section>
    )
  },
)

// src/components/SectionTable.vue
<script setup lang="ts">
import groupBy from 'lodash-es/groupBy'
import { iphoneList } from '../databases/iphone'
import dayjs from 'dayjs'
import { formatDateChinese } from '../modules/date'
import { computed, ref } from 'vue'
import TablePriceByDate from './TablePriceByDate.vue'

const groups = groupBy(
  iphoneList.filter(iphone => iphone.isInitialRelease),
  'releasedAt'
)

const releaseDates = Object.keys(groups)
  .sort((a, b) => +dayjs(b) - +dayjs(a))

const selectedDate = ref<string | null>(releaseDates[0])
const selectedGroup = computed(() => (
  selectedDate.value ? groups[selectedDate?.value] : null
))

const displayed = computed(() => {
  if (selectedGroup.value) {
    return [{ date: selectedDate.value, list: selectedGroup.value }]
  }

  return releaseDates.map((date) => ({ date, list: groups[date] }))
})
</script>

<template>
  <section class="mx-auto flex max-w-5xl flex-col gap-y-8">
    <h2 class="text-3xl font-bold">
      歷年首發機型
    </h2>

    <div class="flex flex-wrap gap-4">
      <div class="relative w-full lg:w-1/5">
        <div class="sticky top-4 flex flex-col gap-y-4">
          <h3 class="text-xl font-medium">
            發售年月
          </h3>
          <ul class="menu rounded-box bg-base-200">
            <li>
              <button
                :class="{ active: !selectedDate }"
                type="button"
                @click="selectedDate = null"
              >
                顯示全部
              </button>
            </li>
            <li v-for="(date, index) in releaseDates" :key="date">
              <button
                :class="{ active: selectedDate === date }"
                type="button"
                @click="selectedDate = date"
              >
                {{ formatDateChinese(date) }}
                <div v-if="!index" class="badge badge-primary badge-sm font-bold">New</div>
              </button>
            </li>
          </ul>
        </div>
      </div>

      <div class="flex min-w-full flex-col sm:mx-0 sm:flex-1 lg:min-w-0 lg:px-8">
        <TablePriceByDate
          v-for="({ date, list }, index) in displayed"
          :key="index"
          :date="date"
          :list="list"
        />
        <span class="text-xs opacity-70">單位：新台幣</span>
      </div>
    </div>
  </section>
</template>
